### ISSUE TITLE
Find usable API

### ISSUE THREAD

**Issue by blakeneely** [blakeneely/project1#6]
## User Story
As a user I want info on players/teams that I choose

## Acceptance Criteria
- [x] Find APIs that work for our scope

## Tasks
1. Research Rapidapi.com for usable sports APIs
2. Apply for any API Keys needed
2. Test APIs to see what info we can get
3. Save usable APIs for implementation later

**Comment by rbartl2** [comment]
https://fantasydata.com/
i think this may be a great option. it says there is a free trial then only 9.99. awesome.

**Comment by rbartl2** [comment]
https://api.stattleship.com/
http://sportsdemo1.gracenote.com/documentation/api

**Comment by blakeneely** [comment]
I think these will work! Perfect!

**Comment by blakeneely** [comment]
Stattleship worked like a charm Rebecca! Onto the next task

**Comment by ewint3** [comment]
dude, thats great news. I cant get to the thread on github to see what to
see it. you'll have to show me how to navigate
